# Generated by Django 2.2.10 on 2020-06-14 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispermit', models.BooleanField(default=False, verbose_name='위치정보 허용동의')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegiProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=20, null=True, verbose_name='1. 펫 이름')),
                ('pet_type', models.CharField(max_length=20, null=True, verbose_name='2. 펫 종류')),
                ('pet_age', models.IntegerField(null=True, verbose_name='3. 펫 나이')),
                ('pet_gender', models.CharField(choices=[('남', '남'), ('여', '여'), ('중성', '중성')], max_length=2, null=True, verbose_name='4. 성별')),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='6. 프로필 사진')),
                ('pet_intro', models.TextField(max_length=100, null=True, verbose_name='7. 소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlusPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='사진 추가하기')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lon', models.DecimalField(decimal_places=20, max_digits=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
