# Generated by Django 2.2.10 on 2020-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_plusphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plusphoto',
            name='plus_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='사진추가하기'),
        ),
    ]
