# Generated by Django 2.2.10 on 2020-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200610_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiprofile',
            name='pet_locate',
            field=models.CharField(max_length=50, null=True, verbose_name='5. 주소'),
        ),
        migrations.AlterField(
            model_name='regiprofile',
            name='pet_intro',
            field=models.CharField(max_length=100, null=True, verbose_name='6. 소개'),
        ),
    ]
