# Generated by Django 2.2.10 on 2020-06-10 12:44

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('accounts', '0006_auto_20200610_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiprofile',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='6. 프로필 사진'),
        ),
        migrations.AlterField(
            model_name='regiprofile',
            name='pet_intro',
            field=models.TextField(max_length=100, null=True, verbose_name='7. 소개'),
        ),
        migrations.AlterField(
            model_name='regiprofile',
            name='pet_locate',
            field=models.TextField(max_length=50, null=True, verbose_name='5. 주소'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
    ]
