# Generated by Django 2.2.10 on 2020-06-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200612_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiprofile',
            name='pet_locate',
        ),
    ]
